---
- hosts: nexus-sonarqube-tomcat
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: root
  vars_files:
    - roles/sonarqube/vars/main.yml
  handlers:
    - include: roles/sonarqube/handlers/main.yml
  roles:
    - role: roles/sonarqube

