---
- hosts: nexus-sonarqube-tomcat
  tasks:
   - name: create directory
     file:
      path: /home/abc2
      owner: root
      group: root
      mode: 0770
      state: directory

        ## Download the sonarqube packages from sonar community 
        #- name: download the sonarqube community
        #shell: 
        #"curl https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.1.0.47736.zip --output /home/abc/sonarqube.zip"

   - name: unarchive sonarqube
     unarchive:
      src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.1.0.47736.zip
      dest: /home/abc2/
      remote_src: yes
      state: directory

   
       #   - name: unzip sonarqube
       #shell:
       #"unzip /home/abc/sonarqube.zip -d /home/abc/"
        

